version: "3"
services:
  hike-tracker-server:
    image: riccardogiambra/hike-tracker-server
    build:
      context: ./server
      dockerfile: ./Dockerfile
      args:
        - JWT_ACC_ACTIVATE=$JWT_ACC_ACTIVATE
        - CLIENT_URL=$CLIENT_URL
        - API_KEY=$API_KEY
    ports:
      - "3001:3001"
  hike-tracker-client:
    image: riccardogiambra/hike-tracker-client
    build:
      context: ./client
    ports:
      - "3000:3000"
#docker-compose up
