name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - 
        name: Docker-Compose Build
        run: |
          docker-compose build
      - 
        name: list images
        run: |
          docker images
      - 
        name: Push server
        run: |
          docker push riccardogiambra/riccardogiambra/hike-tracker-server
      - 
        name: Push client
        run: |
          docker push riccardogiambra/riccardogiambra/hike-tracker-client

